name: The domain of the PREZ
url: http://aniforprez.github.io/
description: The wisdom only obtained through the teachings of the prez

permalink: /:year/:month/:day/:title/
paginate: 15
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']